baseURL = 'https://saalin.dev/'
languageCode = 'en-us'
title = 'Saalin.dev'
theme = 'hugo-theme-console'

enableRobotsTXT = true
enableEmoji = true
paginate = 10
enableGitInfo = true

[sitemap]
  changeFreq = 'daily'
  disable = false
  filename = 'sitemap.xml'