name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 21

    - name: Install dependencies
      run: npm install

    - name: Run npm command
      run: npm run build

    - name: Zip output folder
      run: zip -r build.zip build/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: build.zip
